### ISSUE TITLE
ImportError: No module named 'converter'

### ISSUE THREAD

**Issue by rhiever** [databricks/spark-sklearn#16]
Hello,

I am trying to use the example code from the README for spark-sklearn. I have installed the latest version of Anaconda, and ran `pip install spark_sklearn` to install the package. The following code:

```python
from sklearn import svm, grid_search, datasets
from spark_sklearn import GridSearchCV
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svr = svm.SVC()
clf = GridSearchCV(sc, svr, parameters)
clf.fit(iris.data, iris.target)
```
results in the following traceback:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d38860ad054d> in <module>()
      1 from sklearn import svm, grid_search, datasets
----> 2 from spark_sklearn import GridSearchCV
      3 iris = datasets.load_iris()
      4 parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
      5 svr = svm.SVC()

/Users/randal_olson/anaconda/lib/python3.5/site-packages/spark_sklearn-0.1.1-py3.5.egg/spark_sklearn/__init__.py in <module>()
      1 from scipy.sparse import csr_matrix
      2 
----> 3 from converter import Converter
      4 from grid_search import GridSearchCV
      5 from udt import CSRVectorUDT

ImportError: No module named 'converter'
```

I have tried to install the latest version of spark-sklearn from this repository to no avail. Please advise me how to proceed.

**Comment by rhiever** [comment]
I tried the same code with a Python 2 Anaconda distribution, and received the following traceback:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d38860ad054d> in <module>()
      1 from sklearn import svm, grid_search, datasets
----> 2 from spark_sklearn import GridSearchCV
      3 iris = datasets.load_iris()
      4 parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
      5 svr = svm.SVC()

/Users/randal_olson/anaconda/envs/python2/lib/python2.7/site-packages/spark_sklearn/__init__.py in <module>()
      1 from scipy.sparse import csr_matrix
      2 
----> 3 from converter import Converter
      4 from grid_search import GridSearchCV
      5 from udt import CSRVectorUDT

/Users/randal_olson/anaconda/envs/python2/lib/python2.7/site-packages/spark_sklearn/converter.py in <module>()
     12 from sklearn.linear_model import LinearRegression as SKL_LinearRegression
     13 
---> 14 from pyspark.ml.classification import LogisticRegressionModel
     15 from pyspark.ml.regression import LinearRegressionModel
     16 from pyspark.mllib.linalg import DenseVector, SparseVector, Vectors, VectorUDT

ImportError: No module named pyspark.ml.classification
```

**Comment by thunterdb** [comment]
Hello Randy, can you tell me which version of scikit-learn you are using? You can run:
```python
import sklearn
print sklearn.__version__
```

Also, regarding the second error message, it looks like you are not running the python code within Spark. Please take a look at the [spark website](http://spark.apache.org/docs/latest/quick-start.htm) on how to set it up.

**Comment by rhiever** [comment]
```
In [1]: import sklearn
In [2]: print(sklearn.__version__)
0.17
```

**Comment by zero323** [comment]
@rhiever It looks like an issue with relative imports. You can check #17 and see if it helps.

**Comment by rhiever** [comment]
Please ping me when #17 is merged and uploaded to pip. I was hoping to give this library a spin.

**Comment by thunterdb** [comment]
@rhiever sorry for the delay, I will keep you posted when #17 is merged.

**Comment by thunterdb** [comment]
@rhiever I pushed version `0.1.2` with python 3 support to pypi. I am going to close the ticket, feel free to reopen it if you encounter some issues.

**Comment by manjush3v** [comment]
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spark_sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/spacy/lib/python3.5/site-packages/spark_sklearn/__init__.py", line 3, in <module>
    from spark_sklearn.converter import Converter
  File "/Users/apple/spacy/lib/python3.5/site-packages/spark_sklearn/converter.py", line 14, in <module>
    from pyspark.ml.classification import LogisticRegressionModel
ImportError: No module named 'pyspark'
```

**Comment by thunterdb** [comment]
@manjush3v this seems to be a different issue: you have not loaded pyspark (or spark) into python. Please take a look at the pyspark documentation on how to start python with spark: 
https://spark.apache.org/docs/latest/quick-start.html#basics
