### ISSUE TITLE
error message: sbt.ResolveException: unresolved dependency: org.apache.spark#spark-mllib_2.10;1.6.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by jxiablox** [databricks/spark-sklearn#20]
I clone the repo, and install the following packages, 
1. pip install spark-sklearn
2. pip install nose

also I go to the folder spark-sklearn/python run, 
1. python setup.py build
2. python setup.py install
3. ./run run-tests.sh

Everything looks fine. 

However, when I go to spark-sklearn/ folder and run sbt package, it gave me an error, Please help me what's wrong on my environment. 

Thanks,
Jianhong

[info] Loading project definition from /jianhong/GitHub/spark-sklearn/spark-sklearn/project
[info] Set current project to spark-sklearn (in build file:/jianhong/GitHub/spark-sklearn/spark-sklearn/)
[info] Updating {file:/jianhong/GitHub/spark-sklearn/spark-sklearn/}spark-sklearn...
[info] Resolving org.apache.spark#spark-mllib_2.10;1.6.0-SNAPSHOT ...
[warn]  module not found: org.apache.spark#spark-mllib_2.10;1.6.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/jxia/.ivy2/local/org.apache.spark/spark-mllib_2.10/1.6.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/spark/spark-mllib_2.10/1.6.0-SNAPSHOT/spark-mllib_2.10-1.6.0-SNAPSHOT.pom
[warn] ==== Spark Packages Repo: tried
[warn]   https://dl.bintray.com/spark-packages/maven/org/apache/spark/spark-mllib_2.10/1.6.0-SNAPSHOT/spark-mllib_2.10-1.6.0-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.spark#spark-mllib_2.10;1.6.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.apache.spark:spark-mllib_2.10:1.6.0-SNAPSHOT ((sbtsparkpackage.SparkPackagePlugin) SparkPackagePlugin.scala#L241)
[warn]            +- default:spark-sklearn_2.10:0.0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.apache.spark#spark-mllib_2.10;1.6.0-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
        at sbt.IvySbt.withIvy(Ivy.scala:119)
        at sbt.IvySbt.withIvy(Ivy.scala:116)
        at sbt.IvySbt$Module.withModule(Ivy.scala:147)
        at sbt.IvyActions$.updateEither(IvyActions.scala:156)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-mllib_2.10;1.6.0-SNAPSHOT: not found
[error] Total time: 1 s, completed Apr 13, 2016 4:11:28 PM

**Comment by jxiablox** [comment]
The problem is resolved. 

The issue is that my spark version is 1.6.1. 

I just modify the build.sbt, and change the line 

sparkVersion := "1.6.0-SNAPSHOT"

to

sparkVersion := "1.6.1"

Then I run "sbt package", everything looks fine. 

Thanks,
Jianhong

**Comment by 7873737376** [comment]
Error while importing sbt project:

[info] Loading global plugins from C:\Users\developers\.sbt\0.13\plugins
[info] Loading project definition from C:\Users\developers\IdeaProjects\DisArchTest\project
[info] Set current project to DisArchTest (in build file:/C:/Users/developers/IdeaProjects/DisArchTest/)
>
[info] Defining */*:sbtStructureOptions, */*:sbtStructureOutputFile, *:shellPrompt
[info] The new values will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to DisArchTest (in build file:/C:/Users/developers/IdeaProjects/DisArchTest/)
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from C:/Users/developers/.IdeaIC2018.2/config/plugins/Scala/launcher/sbt-structure-0.13.jar
[info] Reapplying settings...
[info] Set current project to DisArchTest (in build file:/C:/Users/developers/IdeaProjects/DisArchTest/)
[info] Updating {file:/C:/Users/developers/IdeaProjects/DisArchTest/}disarchtest...
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[info] Resolving org.apache.spark#spark-core_2.11;2.2.0.2.6.4.0-91 ...
[info] Resolving org.apache.spark#spark-core_2.11;2.2.0.2.6.4.0-91 ...
[warn] 	module not found: org.apache.spark#spark-core_2.11;2.2.0.2.6.4.0-91
[warn] ==== local: tried
[warn]   C:\Users\developers\.ivy2\local\org.apache.spark\spark-core_2.11\2.2.0.2.6.4.0-91\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\developers\.sbt\preloaded\org.apache.spark\spark-core_2.11\2.2.0.2.6.4.0-91\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/developers/.sbt/preloaded/org/apache/spark/spark-core_2.11/2.2.0.2.6.4.0-91/spark-core_2.11-2.2.0.2.6.4.0-91.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11/2.2.0.2.6.4.0-91/spark-core_2.11-2.2.0.2.6.4.0-91.pom
[info] Resolving org.apache.spark#spark-sql_2.11;2.2.0.2.6.4.0-91 ...
[info] Resolving org.apache.spark#spark-sql_2.11;2.2.0.2.6.4.0-91 ...
[warn] 	module not found: org.apache.spark#spark-sql_2.11;2.2.0.2.6.4.0-91
[warn] ==== local: tried
[warn]   C:\Users\developers\.ivy2\local\org.apache.spark\spark-sql_2.11\2.2.0.2.6.4.0-91\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\developers\.sbt\preloaded\org.apache.spark\spark-sql_2.11\2.2.0.2.6.4.0-91\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/developers/.sbt/preloaded/org/apache/spark/spark-sql_2.11/2.2.0.2.6.4.0-91/spark-sql_2.11-2.2.0.2.6.4.0-91.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/2.2.0.2.6.4.0-91/spark-sql_2.11-2.2.0.2.6.4.0-91.pom
[info] Resolving org.scala-lang#scala-compiler;2.11.7 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.7 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4 ...
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.spark#spark-core_2.11;2.2.0.2.6.4.0-91: not found
[warn] 	:: org.apache.spark#spark-sql_2.11;2.2.0.2.6.4.0-91: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.apache.spark:spark-core_2.11:2.2.0.2.6.4.0-91 (C:\Users\developers\IdeaProjects\DisArchTest\build.sbt#L10-11)
[warn] 		  +- default:disarchtest_2.11:0.1
[warn] 		org.apache.spark:spark-sql_2.11:2.2.0.2.6.4.0-91 (C:\Users\developers\IdeaProjects\DisArchTest\build.sbt#L11-12)
[warn] 		  +- default:disarchtest_2.11:0.1
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-core_2.11;2.2.0.2.6.4.0-91: not found
[error] unresolved dependency: org.apache.spark#spark-sql_2.11;2.2.0.2.6.4.0-91: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-core_2.11;2.2.0.2.6.4.0-91: not found
[error] unresolved dependency: org.apache.spark#spark-sql_2.11;2.2.0.2.6.4.0-91: not found
[error] Total time: 2 s, completed Sep 23, 2018 10:52:05 AM
