### ISSUE TITLE
Error When Calling toPandas()

### ISSUE THREAD

**Issue by sdjksdafji** [databricks/spark-sklearn#49]
Hi,

My scripts are throwing errors when running on clusters:

Converting training data to pandas dataframe
                                                                                
Traceback (most recent call last):
  File "/tmp/49a99d28-350b-4942-ab63-f7efa0d2f0ec/random-forest-sklearn.py", line 244, in <module>
    training_data = sk_converter.toPandas(trainingSet)
  File "/usr/local/lib/python3.4/dist-packages/spark_sklearn/converter.py", line 159, in toPandas
    return df.select(*cols).toPandas()
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 1442, in toPandas
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 311, in collect
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 142, in _load_from_socket
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 139, in load_stream
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 156, in _read_with_length
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 543, in read_int
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
16/12/15 22:49:04 ERROR org.apache.spark.api.python.PythonRDD: Error while sending iterator
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.apache.spark.api.python.PythonRDD$.org$apache$spark$api$python$PythonRDD$$write$1(PythonRDD.scala:492)
	at org.apache.spark.api.python.PythonRDD$$anonfun$writeIteratorToStream$1.apply(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRDD$$anonfun$writeIteratorToStream$1.apply(PythonRDD.scala:504)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:112)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRDD$$anon$2$$anonfun$run$1.apply$mcV$sp(PythonRDD.scala:700)
	at org.apache.spark.api.python.PythonRDD$$anon$2$$anonfun$run$1.apply(PythonRDD.scala:700)
	at org.apache.spark.api.python.PythonRDD$$anon$2$$anonfun$run$1.apply(PythonRDD.scala:700)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1310)
	at org.apache.spark.api.python.PythonRDD$$anon$2.run(PythonRDD.scala:701)
16/12/15 22:49:04 INFO org.spark_project.jetty.server.ServerConnector: Stopped ServerConnector@54284c76{HTTP/1.1}{0.0.0.0:4040}

However, the scripts works totally fine when running on small dataset locally. My memory should be fine. I got roughly 200G memory each machine (both executors and driver) for my cluster. My data is only 16G. Anyone know the possible issue here ? I appreciate your help in advance.

@thunterdb

**Comment by B-Schulz** [comment]
Thanks! This was helpful. Retry function works fine for some reason...

**Comment by B-Schulz** [comment]
Thanks! This was helpful. Retry function works fine for some reason...

**Comment by SemanticBeeng** [comment]
There is a hardcoded timeout value here:

https://github.com/apache/spark/blob/628c7b517969c4a7ccb26ea67ab3dd61266073ca/core/src/main/scala/org/apache/spark/api/python/PythonRDD.scala#L403

```
  def serveIterator(items: Iterator[_], threadName: String): Array[Any] = {
    val serverSocket = new ServerSocket(0, 1, InetAddress.getByName("localhost"))
    // Close the socket if no connection in 15 seconds
    serverSocket.setSoTimeout(15000)

```

**Comment by zouqian2468** [comment]
# Enable Arrow-based columnar data transfers
spark.conf.set("spark.sql.execution.arrow.enabled", "true")

**Comment by zouqian2468** [comment]
#### Enable Arrow-based columnar data transfers
spark.conf.set("spark.sql.execution.arrow.enabled", "true")

**Comment by jasstionzyf** [comment]
@zouqian2468  still error : RuntimeError: could not open socket
it really dispirited  when use pyspark ,  why spark developers can not develop such issues?  
it appear everywhere as long as i use pyspark operation like :  rdd, collect, toPandas

**Comment by aytida** [comment]
I faced a similar issue. Nothing worked until i changed the database completely. I did not understand but it seems like the pyspark dataframe created from SQL server was throwing this error but not the one from Redshift.
