### ISSUE TITLE
Convert IndexError: tuple index out of range

### ISSUE THREAD

**Issue by nlathia** [databricks/spark-sklearn#58]
I am using Python 3.4.5, and spark-2.1.0-bin-hadoop2.7, and sklearn 0.18.2. When I use the `Convert.toSKLearn()` and then try to make predictions, I get a `IndexError: tuple index out of range` error.

Full example below:
```
from pyspark.sql import SparkSession
from pyspark.ml.linalg import Vectors
from pyspark.sql import Row
from pyspark.ml.classification import LogisticRegression
from spark_sklearn import Converter
import numpy as np

spark = SparkSession.builder.getOrCreate()

# Create fake data
features = [
    [1, 0, 0],
    [1, 0, 0],
    [0, 0, 1]
]
labels = [1, 1, 0]

data = []
for i in range(len(features)):
    data.append(
        Row(label=labels[i], features=Vectors.dense(features[i]))
    )

df = spark.sparkContext.parallelize(data).toDF()
df.show()

# Train a model
model = LogisticRegression()
model = model.fit(df)

# Convert to sklearn
converter = Converter(spark.sparkContext)
sk_model = converter.toSKLearn(model)

# Make some predictions
predictions = sk_model.predict_proba(np.vstack(features))
print(predictions)
```
Which raises this:
```
Traceback (most recent call last):
[...]
  File "<path>/.venv/lib/python3.4/site-packages/sklearn/linear_model/logistic.py", line 1286, in predict_proba
    return super(LogisticRegression, self)._predict_proba_lr(X)
  File "<path>/.venv/lib/python3.4/site-packages/sklearn/linear_model/base.py", line 350, in _predict_proba_lr
    prob = self.decision_function(X)
  File "<path>/.venv/lib/python3.4/site-packages/sklearn/linear_model/base.py", line 314, in decision_function
    n_features = self.coef_.shape[1]
IndexError: tuple index out of range
```

It seems that this can be solved by reshaping the coefficients:
```
# Convert to sklearn
converter = Converter(spark.sparkContext)
sk_model = converter.toSKLearn(model)

sk_model.coef_ = sk_model.coef_.reshape(1, -1)  # This is needed!

predictions = sk_model.predict_proba(np.vstack(features))
print(predictions)
```

Is this the right thing to do, or have I missed something?

**Comment by nlathia** [comment]
Related: a call to `predict()` on the sklearn model (after adding in the fix mentioned above: reshaping the coefficients) will raise an AttributeError:

```
# Convert to sklearn
converter = Converter(spark.sparkContext)
sk_model = converter.toSKLearn(model)
predictions = sk_model.predict(np.vstack(features))
print(predictions)
```
Raises:
```
Traceback (most recent call last):
[...]
  File "<path>/.venv/lib/python3.4/site-packages/sklearn/linear_model/base.py", line 341, in predict
    return self.classes_[indices]
AttributeError: 'LogisticRegression' object has no attribute 'classes_'
```
It looks like `convert.py` needs to be setting this attribute as well. The following fixes my example (for binary classification):
```
# Convert to sklearn
converter = Converter(spark.sparkContext)
sk_model = converter.toSKLearn(model)

sk_model.coef_ = sk_model.coef_.reshape(1, -1)  
sk_model.classes_ = np.array([0, 1]) # This is needed!

predictions = sk_model.predict(np.vstack(features))
print(predictions)
```
If these fixes look like the right way to do things, I'd be happy to submit a pull request.

**Comment by gszjulcsi** [comment]
Hi!

I could reproduce the same error with the following configurations:

- Spark 2.1.1 and Python 3.5.2 and spark-sklearn==0.2.0 and scikit-learn==0.17.0
- Spark 2.1.1 and Python 3.5.2 and spark-sklearn==0.2.0  and scikit-learn==0.18.2

**Comment by srowen** [comment]
Sorry for the loong delay. I'm cleaning house now on old issues. This seems like a fine change if it fixes it for you. Indeed the tests don't test whether the model makes a prediction; I think I can add that easily.

**Comment by nlathia** [comment]
Thanks Sean!
