### ISSUE TITLE
ImportError: Module not found with Azure Spark Cluster

### ISSUE THREAD

**Issue by Nimi42** [databricks/spark-sklearn#81]
I'm trying to run spark-sklearns GridSearch on an HDInsight Cluster from Azure. Here is a Code Snippet:

```
        model = KerasRegressor(build_fn=build_model, verbose=0)

        kf = KFold(n_splits=self.cv_split, shuffle=True)  # Cross validation with k=5

        sc = SparkContext.getOrCreate()
        grid = GridSearchCV(sc=sc, estimator=model, param_grid=self.params, 
                            cv=kf, return_train_score=True, verbose=2,
                            fit_params={'epochs': nb_epoch, 'batch_size': 32})

        hist = grid.fit(x_train, y_train)
```

It works fine until I call the grid.fit method, which returns the following exception:

```
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000001/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 4 times, most recent failure: Lost task 2.3 in stage 0.0 (TID 13, wn0-bt-nsu.kkatsjzvwzuephdjshji40kxae.ax.internal.cloudapp.net, executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/worker.py", line 166, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/worker.py", line 55, in read_command
    command = serializer._read_with_length(file)
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/serializers.py", line 455, in loads
    return pickle.loads(obj, encoding=encoding)
ImportError: No module named 'ml'

...

Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/worker.py", line 166, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/worker.py", line 55, in read_command
    command = serializer._read_with_length(file)
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/mnt/resource/hadoop/yarn/local/usercache/nsusshuser/appcache/application_1526397916826_0020/container_e01_1526397916826_0020_01_000002/pyspark.zip/pyspark/serializers.py", line 455, in loads
    return pickle.loads(obj, encoding=encoding)
ImportError: No module named 'ml'
```

The ml module is part of our project. I checked sys.modules and it is in there. Don't really understand the error message. Can somebody help me out?

**Comment by srowen** [comment]
That doesn't seem like an error from spark-sklearn; it's not finding your code, you indicate. It would be something to do with how you are deploying your pyspark app. Have a look at the upstream Apache Spark docs for submitting Python jobs, or try a simple job with your code in your namespace and get that working to rule out spark-sklearn.
